var maincontent = [{
        "room": "roomonebox",
        "roomtitle": "Room 1",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    },{
        "room": "roomtwobox",
        "roomtitle": "Room 2",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    },{
        "room": "roomthreebox",
        "roomtitle": "Room 3",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    },{
        "room": "roomfourbox",
        "roomtitle": "Room 4",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    },{
        "room": "roomfivebox",
        "roomtitle": "Room 5",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    },{
        "room": "roomsixbox",
        "roomtitle": "Room 6",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    },{
        "room": "roomsevenbox",
        "roomtitle": "Room 7",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    },{
        "room": "roomeightbox",
        "roomtitle": "Room 8",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    },{
        "room": "roomninebox",
        "roomtitle": "Room 9",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    },{
        "room": "roomtenbox",
        "roomtitle": "Room 10",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_ans":"answer",
        "roompuzzle_ans_message":"Congratulations", 
        "roompuzzle_ans_message_wrong":"Nope"
    },{
        "room": "roomelevenbox",
        "roomtitle": "Room 11",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    },{
        "room": "roomtwelvebox",
        "roomtitle": "Room 12",
        "roomdescription": "small, dark with a lone window in front, chimney in back, one small bed with a thin mattress in the corner. A chamber pot under the bed, a mirror, slightly askew. Thin and worn fabric pulled to the side of the window on a hook. The window is dark with dust, cobwebs, and dead bugs. A small table in the corner, with a single candle holder with a candle burnt down to the nub. As you move into the room, the change in light and shadow reveals the imprint of a person in the bed.",
        "roompuzzle": "You hear a voice whisper.. what question could I never answer with a yes?",
        "roompuzzle_opt1":"Are you tired?",
        "roompuzzle_opt1_var":"1",
        "roompuzzle_opt2":"Are you asleep?",
        "roompuzzle_opt2_var":"2",
        "roompuzzle_opt3":"Are you happy?",
        "roompuzzle_opt3_var":"3",
        "roompuzzle_ans":"2",
        "roompuzzle_ans_message":"You feel warm and the dead bugs skitter away in the shape of an S", 
        "roompuzzle_ans_message_wrong":"You hear a faint howl and some laughter as the voice fades away."
    }
]

var mainpeople = [{
    "person": "1",
    "person_name": "Name One",
    "person_description": "Person description goes here.",
    "person_motive": "Person Motive Here",
    "Personlead1":"Lead 1",
    "Personlead2":"Lead 2",
    "Personlead3":"Lead 3",
    "Personalibi":"Alibi",
    "Personguilty":"Guilty",
    "Personguilty_message":"Guilty Message", 
    "Personthankyou_message":"Person Thankyou"
},{
    "person": "2",
    "person_name": "Name One",
    "person_description": "Person description goes here.",
    "person_motive": "Person Motive Here",
    "Personlead1":"Lead 1",
    "Personlead2":"Lead 2",
    "Personlead3":"Lead 3",
    "Personalibi":"Alibi",
    "Personguilty":"Guilty",
    "Personguilty_message":"Guilty Message", 
    "Personthankyou_message":"Person Thankyou"
},{
    "person": "3",
    "person_name": "Name One",
    "person_description": "Person description goes here.",
    "person_motive": "Person Motive Here",
    "Personlead1":"Lead 1",
    "Personlead2":"Lead 2",
    "Personlead3":"Lead 3",
    "Personalibi":"Alibi",
    "Personguilty":"Guilty",
    "Personguilty_message":"Guilty Message", 
    "Personthankyou_message":"Person Thankyou"
},{
    "person": "4",
    "person_name": "Name One",
    "person_description": "Person description goes here.",
    "person_motive": "Person Motive Here",
    "Personlead1":"Lead 1",
    "Personlead2":"Lead 2",
    "Personlead3":"Lead 3",
    "Personalibi":"Alibi",
    "Personguilty":"Guilty",
    "Personguilty_message":"Guilty Message", 
    "Personthankyou_message":"Person Thankyou"
}]

var beginandend = [{
    "intro": "1",
    "introstatement": "Introduction to the story.",
    "introchallenge": "This is the challenge.",
    "endchallenge": "The challenge was.",
    "challengeoption1":"Option 1",
    "challengeoption2":"Option 2",
    "challengeoption3":"Option 3",
    "challengeoption4":"Option 4",
    "challengeanswer":"Option 3",
    "end_correct_message":"Correct Message", 
    "end_incorrect_message":"Incorrect Message"
}]

var explorecount = 0