[{
	"stacknumber": "4",
	"intro": "An Oregon Ocean October Walk",
	"introstatement": "Fog rolls in over the nearby mountain as you survey the seemingly endless stretch of sand leading to Nehalem Bay.  The hazy orange sun disappears behind the water and you start your twilight walk from Manzanita to Sunset Beach.",
	"introchallenge": "Outside of town you notice an abandoned house with a golden glow behind one of the broken windows.  A window shutter on the second floor creaks open and a sudden gust causes the house to breathe and creak, creating a sound you could swear said \"trick or treat....\"",
	"roomsetting": "mansion"
}, {
	"room": "roomonebox",
	"roomtitle": "",
	"roomdescription": "",
	"roompuzzle": "",
	"roompuzzle_opt1": "",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "2",
	"roompuzzle_ans_message": "",
	"roompuzzle_ans_message_wrong": ""
}, {
	"room": "roomtwobox",
	"roomtitle": "",
	"roomdescription": "",
	"roompuzzle": "",
	"roompuzzle_opt1": "",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "1",
	"roompuzzle_ans_message": "",
	"roompuzzle_ans_message_wrong": ""
}, {
	"room": "roomthreebox",
	"roomtitle": "",
	"roomdescription": "",
	"roompuzzle_opt1": "",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "3",
	"roompuzzle_ans_message": "",
	"roompuzzle_ans_message_wrong": ""
}, {
	"room": "roomfourbox",
	"roomtitle": "",
	"roomdescription": "",
	"roompuzzle_opt1": "",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "3",
	"roompuzzle_ans_message": "",
	"roompuzzle_ans_message_wrong": ""
}, {
	"room": "roomfivebox",
	"roomtitle": "",
	"roomdescription": "",
	"roompuzzle_opt1": "",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "2",
	"roompuzzle_ans_message": "",
	"roompuzzle_ans_message_wrong": ""
}, {
	"room": "roomsixbox",
	"roomtitle": "bedroom",
	"roomdescription": "As you peer into the dark room, a rusty iron bed frame outlines a riddle written on the floor, illuminated by the open window.  A falsetto voice from the dark reads you the riddle.",
	"roompuzzle": "How do you fix a Jack O Lantern?",
	"roompuzzle_opt1": "light bulb",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "Paper Towel",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "Pumkin Patch",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "3",
	"roompuzzle_ans_message": "You smirk and whisper the answer - the falsetto voice giggles a response - that's right, remember the letters EN.  ",
	"roompuzzle_ans_message_wrong": "You shrug your shoulders and the voice giggles a high pitched response - nooooo ... try harder next time."
}, {
	"room": "roomsevenbox",
	"roomtitle": "Study",
	"roomdescription": "A tattered leather chair sits on its side in front of a three legged desk, dusty books stacked as the fourth leg of the desk.  A single red book sits on the desk with a question mark on the cover and three tabs representing options for an answer.  A deep low voice grumbles the riddle from the closet:",
	"roompuzzle": "How do you spell candy with two letters?",
	"roompuzzle_opt1": "P and E and Z",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "C and Y",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "B and AR",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "2",
	"roompuzzle_ans_message": "You select the tab and the deep low voice booms - bua bua bua .... well done, remember the letters GO.",
	"roompuzzle_ans_message_wrong": "The deep voice groans as you select the wrong tab - uuurrrghaaarrraahh..."
}, {
	"room": "roomeightbox",
	"roomtitle": "",
	"roomdescription": "",
	"roompuzzle": "",
	"roompuzzle_opt1": "",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "3",
	"roompuzzle_ans_message": "",
	"roompuzzle_ans_message_wrong": ""
}, {
	"room": "roomninebox",
	"roomtitle": "",
	"roomdescription": "",
	"roompuzzle_opt1": "",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "1",
	"roompuzzle_ans_message": ""
}, {
	"room": "roomtenbox",
	"roomtitle": "Dining Room",
	"roomdescription": "A stone fireplace with ghostly golden flame illuminates a table in the center of the room with a silver locked box table labeled \"Treats.\" The combination lock requires six letters.  Alieku and Eeek jump up on the table - you notice Alieku's collar shows three pictures from left to right - a piece of candy on the left, a ghost in the middle, and a pumpkin on the right.  Eeek's cloth patch also falls on the table, and it shows sand on the left, the sun in the middle, and a cloud. ",
	"roompuzzle": "All three of the voices you heard in the other rooms speak in a particular order.  First the low voice speaks \"arrange the letters\", second the mid voice utters \"in the order\" and then the high voice screeches \"of pitch and/or picture ... to get the treat.\"  The voices all whisper \"quickly, or we show you a trick ...\"  Eyes of the ghosts appear in the corners of the room.  Select the animal that helps you with the combination and put in the combination.",
	"roompuzzle_ans": "golden",
	"roompuzzle_ans_message": "You see hands reaching toward you from the dark, and nervously fiddle with the lock.  Click, click, click .. each of the letters go into place as a hand brushes your arm.  The last letter falls into place just as you feel yourself lifting from the floor and ... POOF .. the fire illuminates the room, the box opens and the voices say in order - low voice \"wonderful\" mid voice \"job\" high voice \"you did it\" - the room becomes blindingly bright and suddenly you find yourself standing where you started on the beach, no house in sight, and a warm gold coin in your hand.  You look where the house once stood and see a faint shadow of three ghostly figures, oddly sticking out their thumbs.  As you walk to sunset beach you start to wonder if those ghosts followed you all the way from Anaheim, where you vacationed last week.  Darn hitchhikers.",
	"roompuzzle_ans_message_wrong": "You struggle with the lock, and attempt an answer, but when the letters are in place nothing happens.  You feel hands grasping your shoulders and you lift up in the air, the room goes dark, and you suddenly find yourself outside the house, exactly where you started as if time has reset."
}, {
	"room": "roomelevenbox",
	"roomtitle": "Parlor",
	"roomdescription": "Some springs of an old couch rest next to a large old wood and brass radio.  The radio dial has three selections that seem to be possible answers to a riddle.  A calm mid-range voice sings a riddle:",
	"roompuzzle": "What room do ghosts avoid?",
	"roompuzzle_opt1": "Bath Room",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "Bed Room",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "Living Room",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "3",
	"roompuzzle_ans_message": "With a chuckle you move the dial to the right answer and the mid range voice sings \"oooohh ahhhh good job ... remember the letters LD\"",
	"roompuzzle_ans_message_wrong": "You nervously move the dial to an answer and the clearly disappointed mid range voice makes a sound like the air leaving a balloon - pshhhhhhh ... "
}, {
	"room": "roomtwelvebox",
	"roomtitle": "",
	"roomdescription": "",
	"roompuzzle": "",
	"roompuzzle_opt1": "",
	"roompuzzle_opt1_var": "1",
	"roompuzzle_opt2": "",
	"roompuzzle_opt2_var": "2",
	"roompuzzle_opt3": "",
	"roompuzzle_opt3_var": "3",
	"roompuzzle_ans": "3",
	"roompuzzle_ans_message": "",
	"roompuzzle_ans_message_wrong": ""
}, {
	"person": "roomonebox",
	"person_name": "",
	"person_entry": "",
	"person_description": "",
	"person_info1": "",
	"person_info2": ""
}, {
	"person": "roomfivebox",
	"person_name": "",
	"person_entry": "",
	"person_description": "",
	"person_info1": "",
	"person_info2": "",
	"person_end_message": ""
}, {
	"person": "roomtwobox",
	"person_name": "Alieku",
	"person_entry": "",
	"person_description": "",
	"person_info1": "",
	"person_info2": ""
}, {
	"person": "roomsixbox",
	"person_name": "Alieku",
	"person_entry": " the cat saunters up to you.",
	"person_description": "",
	"person_info1": "This kind kitty gently walks next to your leg, nuzzles you, and is wearing collar with pictures you can't quite make out as the kitty saunters out of the room.",
	"person_info2": "",
	"person_end_message": "Your chosen helper, Alieku, appears next to you to join in on the next journey and you now feel safe from any spell, haunt, or ghostly grasp."
}, {
	"person": "roomthreebox",
	"person_name": "Eeek",
	"person_entry": "",
	"person_description": "",
	"person_info1": "",
	"person_info2": ""
}, {
	"person": "roomsevenbox",
	"person_name": "Eeek",
	"person_entry": " the raccoon skitters past you in the room.",
	"person_description": "",
	"person_info1": "you see a flash of a cloth patch in the raccoon's hand as it leaves the room.",
	"person_info2": "",
	"person_end_message": "Eek skitters to the forest, and you feel there is no connection between you and this wild cute little animal."
}, {
	"person": "roomfourbox",
	"person_name": "",
	"person_entry": "",
	"person_description": "",
	"person_info1": "",
	"person_info2": ""
}, {
	"person": "roomeightbox",
	"person_name": "",
	"person_entry": "",
	"person_description": "",
	"person_info1": "",
	"person_info2": "",
	"person_end_message": ""
}]